### ISSUE TITLE
Text box supporting

### ISSUE THREAD

**Issue by coolboy0002001** [xuri/excelize#38]
Suggest to add function "AddTextBox()" like "AddPicture()"

**Comment by Luxurioust** [comment]
@coolboy0002001 Hi, I have add a new function `AddShape()` to support create preset geometry in XLSX. You can add text box by create a `rect` (rectangle) type shape.

**Comment by coolboy0002001** [comment]
It works and I want to know if I could set font-family and font-size.
```
xlsx.AddShape("Sheet1", "A2", `{"format":{"x_offset": 15, "y_offset": 10},"type":"rect", "text":"text","width": 60, "height": 35 }`)
```

**Comment by Luxurioust** [comment]
I have added support for set font style of shape text.

**Comment by Luxurioust** [comment]
Now `AddShape()` has been supported to insert a new line, note that the format set parameter has been changed.
